name = "cf-worker-template"
main = "dist/main.js"
compatibility_date = "2023-03-16"

kv_namespaces = [
    { "id" = "", "binding" = "MY_KV_STORAGE", "preview_id" = "" },
]

[vars]
ENV = "DEVELOPMENT"
JWTsecret = "TEST"

[env.production]
kv_namespaces = [
    { "id" = "", "binding" = "MY_KV_STORAGE", "preview_id" = "" },
]

[env.production.vars]
ENV = "PRODUCTION"
JWTsecret = "SECRET"